[package]
name = "line-parser"
version = "2019.11.9"
authors = ["fuyutarow <fuyutarow@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.9"
toml = "0.5.5"
serde_derive = "1.0.102"
serde = "1.0.102"
regex = "1.3.1"
structopt = "0.3.4"
